# Traversability map filter parameters
traversability_map_filters:
  - name: surfaceNormalsFilter
    type: gridMapFilters/NormalVectorsFilter
    params:
      input_layer: elevation
      output_layers_prefix: surface_normal_
      radius: 0.2
      normal_vector_positive_axis: z
  - name: slopeFilter
    type: traversabilityFilters/SlopeFilter
    params:
      map_type: traversability_slope
      critical_value: 1.3
  - name: roughnessFilter
    type: traversabilityFilters/RoughnessFilter
    params:
      map_type: traversability_roughness
      critical_value: 0.1
      estimation_radius: 0.1
  - name: weightedSumFilter
    type: gridMapFilters/MathExpressionFilter
    params:
      output_layer: traversability
      expression: (1.0 / 10.0) * (8 * traversability_slope +  2 * traversability_roughness)
  - name: deletionFilter
    type: gridMapFilters/DeletionFilter
    params:
      layers: [surface_normal_x, surface_normal_y, surface_normal_z]

