######################################################### teb_local_planner_tutorials #########################################################

#---standard pioneer footprint---
#---(in meters)---
#footprint: [[-0.26, -0.26], [-0.26, 0.26], [0.26, 0.26], [0.26, -0.26]]
robot_radius: 0.5
#footprint_padding: 0.0

transform_tolerance: 0.2
map_type: "costmap"
subscribe_to_updates: true

always_send_full_costmap: true

obstacle_layer:
  enabled: true
  obstacle_range: 8.0
  raytrace_range: 10.0
  inflation_radius: 1.6
  track_unknown_space: true #true needed for disabling global path planning through unknown space
  combination_method: 1
  #  origin_z: 0.120
  #  z_resolution: 0.01
  #  z_voxels: 1
  #  publish_voxel_map: false
  observation_sources: "laser_scan_sensor"
  laser_scan_sensor:
    #sensor_frame: "hokuyo"
    data_type: "LaserScan"
    topic: "scan"
    marking: true
    clearing: true
    #  laser_scan_sensor:
    #   data_type: "LaserScan"
    #   topic: "scan" # Your LaserScan topic
    #   marking: true
    #   clearing: true
    #   inf_is_valid: true # This parameter does the trick!
    #   min_obstacle_height: 0.120
    #   max_obstacle_height: 0.130


inflation_layer:
  enabled:              true
  cost_scaling_factor:  10.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     1.6  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true
  map_topic:            "map"