######################################################### teb_local_planner_tutorials #########################################################

global_costmap:
  global_frame: "map"
  #global_frame: "base_link"
  robot_base_frame: "base_link"
  update_frequency: 1.0
  publish_frequency: 1.0
  use_dijkstra: false
  static_map: true
  track_unknown_space: true #
  resolution: 0.05
 
  transform_tolerance: 0.5
  plugins:
    - {name: "static_layer", type: "costmap_2d::StaticLayer"}
    #- {name: "obstacle_layer", type: "costmap_2d::VoxelLayer"}
    - {name: "obstacle_layer", type: "costmap_2d::ObstacleLayer"}
    - {name: "inflation_layer", type: "costmap_2d::InflationLayer"}